import 'package:equatable/equatable.dart';

enum AlertStatus {
  unresolved('UNRESOLVED'),
  acknowledged('ACKNOWLEDGED'),
  resolved('RESOLVED'),
  unknown('UNKNOWN');

  const AlertStatus(this.code);

  final String code;

  static AlertStatus fromCode(String? code) {
    for (final value in values) {
      if (value.code == code) return value;
    }
    return AlertStatus.unknown;
  }
}

enum AlertSeverity {
  low('LOW'),
  warning('WARNING'),
  critical('CRITICAL'),
  unknown('UNKNOWN');

  const AlertSeverity(this.code);

  final String code;

  static AlertSeverity fromCode(String? code) {
    for (final value in values) {
      if (value.code == code) return value;
    }
    return AlertSeverity.unknown;
  }
}

/// `DeviationAlertResource`. Alerts are generated by the platform; the mobile
/// app only reads them and performs the review lifecycle transitions.
final class DeviationAlert extends Equatable {
  const DeviationAlert({
    required this.id,
    required this.equipmentId,
    required this.parameterName,
    required this.status,
    required this.severity,
    this.batchId,
    this.recordedValue,
    this.thresholdValue,
    this.unit,
    this.timestamp,
    this.rawTimestamp,
    this.acknowledgedBy,
    this.resolvedBy,
    this.resolutionNotes,
  });

  final int id;
  final int equipmentId;
  final int? batchId;
  final String parameterName;
  final double? recordedValue;
  final double? thresholdValue;
  final String? unit;
  final DateTime? timestamp;
  final String? rawTimestamp;
  final AlertSeverity severity;
  final AlertStatus status;
  final int? acknowledgedBy;
  final int? resolvedBy;
  final String? resolutionNotes;

  bool get isOpen => status != AlertStatus.resolved;
  bool get isCritical => severity == AlertSeverity.critical;

  /// Lifecycle offered by the backend: UNRESOLVED → ACKNOWLEDGED → RESOLVED
  /// (RESOLVED may also be reached directly from UNRESOLVED).
  bool get canAcknowledge => status == AlertStatus.unresolved;
  bool get canResolve => status == AlertStatus.unresolved || status == AlertStatus.acknowledged;

  /// Open critical alerts first, then newest first (same order as Web).
  static int compareByPriority(DeviationAlert a, DeviationAlert b) {
    final open = (b.isOpen ? 1 : 0).compareTo(a.isOpen ? 1 : 0);
    if (open != 0) return open;
    final critical = (b.isCritical ? 1 : 0).compareTo(a.isCritical ? 1 : 0);
    if (critical != 0) return critical;
    final left = a.timestamp;
    final right = b.timestamp;
    if (left == null && right == null) return b.id.compareTo(a.id);
    if (left == null) return 1;
    if (right == null) return -1;
    return right.compareTo(left);
  }

  @override
  List<Object?> get props => [
    id,
    equipmentId,
    batchId,
    parameterName,
    recordedValue,
    thresholdValue,
    unit,
    timestamp,
    rawTimestamp,
    severity,
    status,
    acknowledgedBy,
    resolvedBy,
    resolutionNotes,
  ];
}

/// Aggregated counters for the alerts screen.
final class AlertSummary extends Equatable {
  const AlertSummary({
    required this.total,
    required this.unresolved,
    required this.acknowledged,
    required this.resolved,
    required this.critical,
  });

  factory AlertSummary.of(List<DeviationAlert> alerts) => AlertSummary(
    total: alerts.length,
    unresolved: alerts.where((a) => a.status == AlertStatus.unresolved).length,
    acknowledged: alerts.where((a) => a.status == AlertStatus.acknowledged).length,
    resolved: alerts.where((a) => a.status == AlertStatus.resolved).length,
    critical: alerts.where((a) => a.isCritical && a.isOpen).length,
  );

  final int total;
  final int unresolved;
  final int acknowledged;
  final int resolved;

  /// Critical alerts that are still open.
  final int critical;

  int get open => unresolved + acknowledged;

  @override
  List<Object?> get props => [total, unresolved, acknowledged, resolved, critical];
}

/// `ComplianceEventResource`.
final class ComplianceEvent extends Equatable {
  const ComplianceEvent({
    required this.id,
    required this.eventType,
    this.relatedEntityId,
    this.description,
    this.timestamp,
    this.rawTimestamp,
    this.resolvedBy,
  });

  final int id;
  final String eventType;
  final int? relatedEntityId;
  final String? description;
  final DateTime? timestamp;
  final String? rawTimestamp;
  final int? resolvedBy;

  @override
  List<Object?> get props => [id, eventType, relatedEntityId, description, timestamp, rawTimestamp, resolvedBy];
}

abstract interface class ComplianceRepository {
  Future<List<DeviationAlert>> getEquipmentAlerts(int equipmentId);
  Future<List<DeviationAlert>> getBatchAlerts(int batchId);
  Future<DeviationAlert> getAlert(int alertId);
  Future<DeviationAlert> acknowledge({required int alertId, required int performedBy});
  Future<DeviationAlert> resolve({
    required int alertId,
    required int performedBy,
    required String resolutionNotes,
  });
  Future<List<ComplianceEvent>> getEquipmentEvents(int equipmentId);
  Future<List<ComplianceEvent>> getBatchEvents(int batchId);
}
